const { defineConfig } = require('cypress');

module.exports = defineConfig({
	video: false,
	defaultCommandTimeout: 10000,
	chromeWebSecurity: false,
	watchForFileChanges: false,
	viewportWidth: 1920,
	viewportHeight: 1080,
	waitForAnimations: true,
	animationDistanceThreshold: 20,
	execTimeout: 30000,
	taskTimeout: 30000,
	pageLoadTimeout: 30000,
	requestTimeout: 20000,
	responseTimeout: 20000,
	failOnStatusCode: false,
	screenshotsFolder: 'cypress/screenshots',
	screenshotOnRunFailure: true,
	retries: { runMode: 2, openMode: 1 },
	env: {
		url: '',
		login: '',
		pass: '',
	},
	experimentalSourceRewriting: false,
	fixturesFolder: 'cypress/fixtures',
	e2e: {
		setupNodeEvents(on, config) {},
		baseUrl: 'http://localhost:4700',
		excludeSpecPattern: 'testTest.spec.js',
		specPattern: 'cypress/e2e/**/*.{js,jsx,ts,tsx}',
		supportFile: './cypress/support/e2e.js',
	},
});
